trigger:
- main  # Adjust branch name as needed

pool:
  vmImage: 'ubuntu-latest'  # Use Microsoft-hosted agent

variables:
  ACR_NAME: 'filestreamingcontainerregistry'  # Change this to your ACR name
  IMAGE_NAME: 'filestreamingapp'  # Change this to your app name
  TAG: 'latest'  # Change if needed
  DEPLOYMENT_FOLDER: '/opt/deployment'  # Folder where deployment files will be placed
  VM_IP: '$(VM_IP)'  # This should be set in Azure DevOps pipeline variables

stages:
- stage: BuildAndPush
  displayName: 'Build and Push Docker Image'
  jobs:
  - job: BuildAndPushJob
    displayName: 'Build and Push'
    steps:

    # Ensure the repository files are downloaded
    - checkout: self  

    - task: AzureCLI@2
      displayName: 'Login to Azure'
      inputs:
        azureSubscription: 'RM'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az acr login --name $(ACR_NAME)

    - task: Docker@2
      displayName: 'Build Docker Image'
      inputs:
        command: 'build'
        Dockerfile: '**/Dockerfile'
        repository: '$(ACR_NAME).azurecr.io/$(IMAGE_NAME)'
        tags: '$(TAG)'

    - task: Docker@2
      displayName: 'Push Docker Image to ACR'
      inputs:
        command: 'push'
        repository: '$(ACR_NAME).azurecr.io/$(IMAGE_NAME)'
        tags: '$(TAG)'

- stage: DeployToVM
  displayName: 'Deploy Docker Image to VM'
  jobs:
  - job: DeployJob
    displayName: 'Deploy Docker Image'
    steps:

    - task: SSH@0
      displayName: 'Authenticate Azure CLI'
      inputs:
        sshEndpoint: 'file-streaming-vm-v4'
        runOptions: 'inline'
        inline: |
          echo "Authenticating Azure CLI..."
          az login --service-principal -u $(SP_APP_ID) -p $(SP_PASSWORD) --tenant $(TENANT_ID) || { echo "Azure CLI authentication failed!"; exit 1; }

    - task: SSH@0
      displayName: 'Clean Up Existing Containers'
      inputs:
        sshEndpoint: 'file-streaming-vm-v4'
        runOptions: 'inline'
        inline: |
          echo "Stopping and removing existing container if it exists..."
          EXISTING_CONTAINER=$(docker ps -q --filter "name=$(IMAGE_NAME)")
          if [ ! -z "$EXISTING_CONTAINER" ]; then
            docker stop $EXISTING_CONTAINER
            docker rm $EXISTING_CONTAINER
            echo "Existing container stopped and removed."
          else
            echo "No existing container found."
          fi

          echo "Checking if port 3000 is in use..."
          if sudo lsof -i:3000 -t; then
            echo "Port 3000 is in use. Freeing it..."
            sudo fuser -k 3000/tcp
          else
            echo "Port 3000 is free."
          fi

    - task: SSH@0
      displayName: 'Pull and Run Docker Image'
      inputs:
        sshEndpoint: 'file-streaming-vm-v4'
        runOptions: 'inline'
        inline: |
          echo "Logging into ACR..."
          az acr login --name $(ACR_NAME) || { echo "Failed to log into ACR!"; exit 1; }

          echo "Pulling Docker image..."
          docker pull $(ACR_NAME).azurecr.io/$(IMAGE_NAME):$(TAG) || { echo "Failed to pull Docker image!"; exit 1; }

          echo "Checking if port 3000 is available..."
          if sudo lsof -i:3000 -t; then
            echo "Port 3000 is occupied. Assigning a different port..."
            HOST_PORT=3001
          else
            HOST_PORT=3000
          fi

          echo "Running Docker container on port $HOST_PORT..."
          docker run -d -p $HOST_PORT:3000 --name $(IMAGE_NAME) $(ACR_NAME).azurecr.io/$(IMAGE_NAME):$(TAG) || { echo "Failed to run Docker container!"; exit 1; }

          echo "Container successfully started on port $HOST_PORT."
