trigger:
  branches:
    include:
      - main

variables:
  acrName: 'filestreamingcontainerregistry'                           # ACR name without .azurecr.io
  acrLoginServer: 'filestreamingcontainerregistry.azurecr.io'        # ACR login server
  imageName: 'filestreamingapp'               # Docker image name
  buildVersion: '$(Build.BuildId)'          # Versioned tag
  containerRegistry: 'AzureRM'                # Azure Container Registry service connection name

stages:
- stage: Build
  displayName: 'Build and Push Docker Image'
  jobs:
    - job: Build1
      displayName: 'Build and Push'
      pool:
        vmImage: 'ubuntu-latest'
      steps:
        - task: Docker@2
          inputs:
            command: buildAndPush
            repository: $(acrLoginServer)/$(imageName)
            dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
            containerRegistry: $(containerRegistry)
            tags: |
              $(buildVersion)
              latest
          displayName: 'Build and Push Docker Image'

        - task: Docker@2
          inputs:
            command: tag
            repository: $(acrLoginServer)/$(imageName)
            tags: |
              $(buildVersion)
              latest
            containerRegistry: $(containerRegistry)
          displayName: 'Tag Docker Image'
