apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: backend-image:latest 
          imagePullPolicy: Never  
          ports:
            - containerPort: 3000
          volumeMounts:
            - mountPath: /usr/src/app/merged
              name: upload-volume
      volumes:
        - name: upload-volume
          emptyDir: {} 

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort

