version: '3'
services:
  app:
    image: filestreamingcontainerregistry.azurecr.io/filestreamingapp:latest
    ports:
      - "3000:3000"
    networks:
      - app-network


networks:
  app-network:
    driver: bridge
