version: '3'
services:
  app:
    container_name: app-container
    image: filestreamingcontainerregistry.azurecr.io/filestreamingapp:latest
    ports:
      - "3000:3000"
    networks:
      - app-network

  frontend:
    image: filestreamingcontainerregistry.azurecr.io/filestreaming-frontend:latest
    ports:
      - "3001:3001"
    networks:
      - app-network
    depends_on:
      - app


networks:
  app-network:
    driver: bridge
