version: '3'
services:
  app:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/usr/src/app
    networks:
      - app-network


networks:
  app-network:
    driver: bridge
