version: '3'
services:
  app:
    image: filestreamingcontainerregistry.azurecr.io/filestreamingapp:local-test
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/usr/src/app
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "3001:3001"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
